#+title: Java Basics "Cheat Sheet"
#+DESCRIPTION: An org document of the basics of java in a "Quick Cheat Sheet".
#+author: Leonardo Noriega
#+date: <2022-11-17 Thu>

* TABLE OF CONTENTS :toc:
- [[#commenting-on-java][Commenting on Java]]
  - [[#there-are-2-types-of-comments][There are 2 types of comments:]]
- [[#main-method][Main method]]
- [[#variables][Variables]]
  - [[#types-of-variables][Types of Variables]]
  - [[#defining-variables-and-storing-values-in-variables][Defining variables and storing values in variables]]
- [[#operators][Operators]]
  - [[#all-arithmetic-operators-in-java][All arithmetic operators in java]]
- [[#disclaimer][DISCLAIMER]]

* Commenting on Java
As developers we are always told to commment our code beacuse it's a good practice for the reliability and organization of our code, commenting the code has helped me in *many* situations and nowadays I understand why it is a "good practice" to always do it so that's why it's the first thing I'm showing in this "cheat-sheet".
** There are 2 types of comments:
*** This is a *single-line* comment just start with "//"
#+begin_src java
public class Main{
    public static void main(String[] args){
        //System.out.println("This line is commented");
        System.out.println("This line is not commented");
    }
}
#+end_src
*** This is a *multi-line* comment start with a " /* " and end with " */ "
#+begin_src java
public class Main{
    public static void main(String[] args){
        /*This whole block is commented
          Code is not gonna read any this
          System.out.println("This line is commented");
          */
        System.out.println("This line is not commented");
    }
}
#+end_src
* Main method
If you are using and IDE for java you probbably are getting this "Main method" automatically, but what if you wanted to start practicing all the basics right now on your plain text editor?
Java it's kinda "picky" for starting a project, you will need mandatory a class name and that class need to match the filename, so lets suposse we create a file with the following name: "JavaBasics.java" in order to compile your code you will need to always add the ".java" at the end.
So now that your file has been created with the name "JavaBasics.java" let's see how your main method should be written to work correctly.
#+begin_src java
public class JavaBasics {
    //The only thing that you will change in your code it's your filename instead of "JavaBasics"
    public static void main(String[] args){
    }
}
#+end_src
* Variables
** Types of Variables
- String: This variable stores text and it *needs to be surrounded by double quotes* "Like this".
- int: This variable stores integres so postive or negative numbers with *NO* decimalsi such as 10, 233 or -1, -167.
- float: This variable stores "floating" numbers so this variable *DOES* accept decimals such as 7.25 or -7.25.
- char: This variable stores single characters such as "a", "b" or "A", "B" and again the character *needs to be surrounded by double quotes*.
- boolean: Pretty explanatory, right? Stores boolean values either *true* or *false*.
** Defining variables and storing values in variables
#+begin_src java
public class Main {
    public static void main(String[] args){
        String String1 = "Leonardo";
        int integrer1 = 12;
        float float1 = 7.25f;
        char character1 = 'a';
        Boolean boolean1 = true;
        //"Printing" all the stored values by calling the variables. Don't worry you will learn what this "printing" is.
        System.out.println(String1 + " " + integrer1 + " " + float1 + " " + character1 + " " + boolean1);
    }
}
#+end_src
#+RESULTS:
: Leonardo 12 7.25 a true

* Operators
** All arithmetic operators in java
| Operator | Name           | Description                      | Example | Output |
|----------+----------------+----------------------------------+---------+--------|
| "+"      | Addition       | Adds a values a value to another | 3 + 5   |      8 |
| "-"      | Subtraction    | Subtracts one value from another | 3 - 5   |     -2 |
| "*"      | Multiplication | Multiples values                 | 3 * 5   |     15 |
| "/"      | Division       | Divides one value by another     | 3 / 5   |    0.6 |
| "%"      | Modulus        | Returns the division remainder   | 3 % 5   |      3 |
| "++"     | Increment      | Increase a stored value by 1     | ++3     |      4 |
| "--"     | Decrement      | Decrease a stored value by 1     | --3     |      2 |


* DISCLAIMER
Copyright (c) 2022 Leonardo Noriega
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
